name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: dist

      - name: Run unit tests
        run: npm test

  cypress:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec: [
          "cypress/e2e/test-suite-1/*.cy.js",
          "cypress/e2e/test-suite-2/*.cy.js",
          "cypress/e2e/test-suite-3/*.cy.js"
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Start the server
        run: npm run dev &

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:5173

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          command: npx cypress run --config-file cypress.config.js --spec ${{ matrix.spec }}

      - name: Upload Cypress test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: cypress/reports