name: CI

# Trigger the workflow on push or pull request events on the main branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Log current directory
        run: pwd # Print current directory

      - name: List all files and folders in root
        run: ls -la # List everything in the root directory

      - name: List contents of the dist directory
        run: ls -la dist # Check if 'dist' exists and list its contents

      - name: Upload build artifacts
        if: success() # Only upload if the build and directory checks succeed
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./dist

      - name: Run tests
        run: npm test