name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: dist

      - name: Run unit tests
        run: npm test

  cypress:
    needs: test
    runs-on: ubuntu-latest
    services:
      web:
        image: node:20
        env:
          NODE_ENV: development
        ports:
          - 5173:5173
        options: >-
          --health-cmd "curl -f http://localhost:5173 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: cypress/included:12.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cypress
        env:
          CYPRESS_BASE_URL: http://localhost:5173